services:
  client:
    depends_on:
      - internal
    image: ghcr.io/$REGISTRY_NAME/client:$BRANCH
    command: sh -c "sleep 15 && npm run test:integration"

    environment:
      - THRIFT_HOST=internal
      - THRIFT_PORT=9090

  internal:
    image: ghcr.io/$REGISTRY_NAME/internal:$BRANCH
    command: gradle --no-daemon run -x compileThrift
