/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package internalcrm;

import internalcrm.repositories.LeadRepository;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        LeadRepository.getInstance().findAll().forEach(lead -> System.out.println(lead));
    }
}
