
services:
  virtual:
    depends_on:
      - internal
    build: 
      context: ../../../
      dockerfile: docker/dockerfiles/VirtualCRM/main.Dockerfile

    command: sh -c "gradle test integrationTest --info"

    environment:
      - INTERNAL_CRM_URL=internal
      - INTERNAL_CRM_POST=9090
      - SALESFORCE_USERNAME=${SALESFORCE_USERNAME}
      - SALESFORCE_PASSWORD=${SALESFORCE_PASSWORD}
      - SALESFORCE_BASE_PATH=${SALESFORCE_BASE_PATH}
      - SALESFORCE_CLIENT_SECRET=${SALESFORCE_CLIENT_SECRET}
      - SALESFORCE_CLIENT_ID=${SALESFORCE_CLIENT_ID}


  internal:
    build: 
      context: ../../../
      dockerfile: docker/dockerfiles/InternalCRM/main.Dockerfile
    
    command: gradle run

