
services:
  virtual:
    depends_on:
      - internal
    build: 
      context: ../../../
      dockerfile: docker/dockerfiles/VirtualCRM/main.Dockerfile

    command: sh -c "gradle test integrationTest"

    environment:
      - INTERNAL_CRM_URL=internal
      - INTERNAL_CRM_POST=9090

  internal:
    build: 
      context: ../../../
      dockerfile: docker/dockerfiles/InternalCRM/main.Dockerfile
    
    command: gradle run

