name: CICD

on:
  push:
  pull_request:
    branches: ["master", "dev"]

permissions:
  contents: read

jobs:
  build-thrift:
    name: "build-thrift"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: action/checkout@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: build-push
        uses: docker/build-push-action@v3
        with:
          context: ./thrift
          tags: ghcr.io/${{ github.repository_owner }}/thrift:${{ github.ref_name }}
          push: true
          file: ./docker/dockerfiles/Thrift

  # build:
  #   name: "build"
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Checkout
  #       uses: actions/checkout@v3
  #     - name: Install thrift compiler
  #       run: sudo apt-get update && sudo apt-get install -y libthrift-java thrift-compiler
  #     - name: Install jdk
  #       uses: actions/setup-java@v3
  #       with:
  #         java-version: "17"
  #         distribution: "temurin"
  #     - name: Build java apps
  #       uses: gradle/gradle-build-action@v2.6.0
  #       with:
  #         arguments: assemble
